import { Project } from "../types/interfaces";

export const projectsMock: Project[] = [
  {
    id: 1,
    name: "Prueba",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 2,
    name: "Prueba2",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 3,
    name: "Prueba3",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 4,
    name: "Prueba4",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 5,
    name: "Prueba5",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 6,
    name: "Prueba6",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 7,
    name: "Prueba7",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 8,
    name: "Prueb8",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 9,
    name: "Prueb9",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  {
    id: 10,
    name: "Prueba10",
    description: "lorem ipsum",
    projectManager: "Walt Cosani",
    assignedTo: "Ignacio Truffa",
    status: "enabled",
    creationDate: "09/09/09 18:00 am",
    image: "https://picsum.photos/200",
  },
  ];